import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import type { PropsWithChildren } from 'react';

import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: Readonly<PropsWithChildren>) => (
  <html lang="en">
    <head>
      <meta name="darkreader-lock" />
    </head>
    <body className={inter.className}>{children}</body>
  </html>
);

// biome-ignore lint/style/noDefaultExport: next
export default RootLayout;
