import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import type { FunctionComponent, PropsWithChildren } from 'react';

import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout: FunctionComponent<PropsWithChildren> = ({ children }) => (
  <html lang="en" className="h-full">
    <head>
      <meta name="darkreader-lock" />
    </head>
    <body
      className={`${inter.className} bg-gradient-to-bl from-indigo-600 via-sky-600 to-teal-600 text-sky-300`}
    >
      {children}
    </body>
  </html>
);

// biome-ignore lint/style/noDefaultExport: next
export default RootLayout;
